version: '3.7'

x-deploy-environment: &x-deploy-environment
  BACKEND_BUCKET: 
  BACKEND_REGION: 
  BACKEND_DYNAMODB_TABLE: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_DEFAULT_REGION: 
  TF_VAR_lambda_exec_arn: 
  TF_VAR_apigw_id: 
  TF_VAR_apigw_root_resource_id: 
  TF_VAR_apigw_execution_arn: 
  TF_VAR_lambda_s3_bucket: 
  TF_VAR_aws_username: 
  TF_VAR_apigw_stage:
  TF_VAR_lambda_version:
  TF_VAR_environment_variables:

services:
  test:
    image: cors-proxy
    build:
      context: .
      cache_from:
        - cors-proxy
        - $IMAGES_DOMAIN/cors-proxy
    command: yarn test-and-report
    environment:
      COVERALLS_REPO_TOKEN:
    # volumes:
    #   - .:/app

  terraform_deploy:
    build:
      context: deploy/
    command: ["terraform", "apply", "-auto-approve"]
    # env_file: dev.env
    environment:
      <<: *x-deploy-environment
      BACKEND_KEY: lambdas/tf_state/cors-proxy
      TF_VAR_lambda_function_name: cors-proxy
      TF_VAR_lambda_description: "Cors-proxy has an approved list of domains that it can proxy URLs from, mainly used for loading RSS feeds and the like."
      TF_VAR_lambda_handler: handler.corsProxy
      TF_VAR_lambda_runtime: nodejs12.x
      TF_VAR_lambda_method: GET
      TF_VAR_lambda_memory_limit: 1024

  build_lambda:
    image: cors-proxy-build
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        production: "true"
    command: sh -c 'mkdir dist; cat .lambdafiles | xargs zip -r -9 -q ./dist/cors-proxy.zip'
    labels:
      - 'nyulibraries.app=cors-proxy'
