version: '3.7'

x-deploy-environment: &x-deploy-environment
  BACKEND_BUCKET: 
  BACKEND_REGION: 
  BACKEND_DYNAMODB_TABLE: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_DEFAULT_REGION: 
  TF_VAR_lambda_exec_arn: 
  TF_VAR_apigw_id: 
  TF_VAR_apigw_root_resource_id: 
  TF_VAR_apigw_execution_arn: 
  TF_VAR_lambda_s3_bucket: 
  TF_VAR_aws_username: 
  TF_VAR_apigw_stage:
  TF_VAR_lambda_version:
  TF_VAR_environment_variables:
  ALLOW_ORIGINS:

services:
  test:
    image: cors-proxy
    build:
      context: .
      dockerfile: Dockerfile.node
      cache_from:
        - cors-proxy
        - quay.io/nyulibraries/cors-proxy
    command: yarn test-and-report
    environment:
      COVERALLS_REPO_TOKEN: 
    volumes:
      - .:/app

  fn_create:
    image: cors-proxy-create
    build:
      context: .
      dockerfile: Dockerfile.deploy
    environment:
      <<: *x-environment
    entrypoint: ["./create.sh"]
  
  fn_destroy:
    image: cors-proxy-destroy
    build:
      context: .
      dockerfile: Dockerfile.deploy
    environment:
      <<: *x-environment
    entrypoint: ["./destroy.sh"]

  build_lambda:
    image: cors-proxy-build
    build: 
      context: .
      dockerfile: Dockerfile.node
      args:
        production: "true"
    command: sh -c 'mkdir dist; cat .lambdafiles | xargs zip -r -9 -q ./dist/cors-proxy.zip'
    labels:
      - 'nyulibraries.app=cors-proxy'
